CREATE TABLE IF NOT EXISTS users (
    USER_ID UUID PRIMARY KEY,
    DOCUMENT_TYPE VARCHAR(255),
    DOCUMENT_NUMBER LONG,
    NAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    EMAIL VARCHAR(255)
                                 );
CREATE TABLE IF NOT EXISTS book (
    BOOK_ID UUID PRIMARY KEY,
    TITLE VARCHAR(255),
    AUTHOR VARCHAR(255),
    GENRE VARCHAR(255),
    STATE VARCHAR(255),
    USER_ID UUID,
    FOREIGN KEY (USER_ID) REFERENCES users(USER_ID)
);
CREATE TABLE IF NOT EXISTS exchange_request (
    EXCHANGE_ID UUID PRIMARY KEY,
    STATE VARCHAR(255),
    USER_ID UUID,
    BOOK UUID,
    FOREIGN KEY (USER_ID) REFERENCES users(USER_ID),
    FOREIGN KEY (BOOK) REFERENCES book(BOOK_ID)
                                            );
CREATE TABLE IF NOT EXISTS review (
    REVIEW_ID UUID PRIMARY KEY,
    TEXT VARCHAR(255),
    SCORE DOUBLE,
    USER_ID UUID,
    BOOK UUID,
    FOREIGN KEY (USER_ID) REFERENCES users(USER_ID),
    FOREIGN KEY (BOOK) REFERENCES book(BOOK_ID)
                                  );
