CREATE TABLE IF NOT EXISTS users (
    USER_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DOCUMENT_TYPE VARCHAR(255),
    DOCUMENT_NUMBER LONG,
    NAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    EMAIL VARCHAR(255)
                                 );
CREATE TABLE IF NOT EXISTS book (
    BOOK_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255),
    AUTHOR VARCHAR(255),
    GENRE VARCHAR(255),
    STATE VARCHAR(255),
    USER_ID INTEGER,
    FOREIGN KEY (USER_ID) REFERENCES users(USER_ID)
);
CREATE TABLE IF NOT EXISTS exchange_request (
    EXCHANGE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    STATE VARCHAR(255),
    USER_ID INTEGER,
    BOOK INTEGER,
    FOREIGN KEY (USER_ID) REFERENCES users(USER_ID),
    FOREIGN KEY (BOOK) REFERENCES book(BOOK_ID)
                                            );
CREATE TABLE IF NOT EXISTS review (
    REVIEW_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TEXT VARCHAR(255),
    SCORE DOUBLE,
    USER_ID INTEGER,
    BOOK INTEGER,
    FOREIGN KEY (USER_ID) REFERENCES users(USER_ID),
    FOREIGN KEY (BOOK) REFERENCES book(BOOK_ID)
                                  );
